export const ERROR_MESSAGE = {
  WALLET_NOT_CONNECTED: 'You need to connect wallet first.',
  NO_ROUTES_FOUND: 'No routes found',
  NO_PSM_FOUND: 'No PSM found',
  INVALID_INPUT: 'Invalid input.',
  AMOUNT_NOT_SPECIFIED: {
    DEFAULT: 'Enter an amount',
    DEPOSIT: 'Enter deposit amount',
    BORROW: 'Enter borrow amount',
    WITHDRAW: 'Enter withdraw amount',
    REPAY: 'Enter repay amount',
    STAKE: 'Enter stake amount',
    UNSTAKE: 'Enter unstake amount',
  },
  INSUFFICIENT_BALANCE: 'Insufficient balance',
  INSUFFICIENT_STAKE_AMOUNT: 'Your staked amount is not enough.',
  NO_TOKEN_SELECTED: 'You need to choose a token.',
  NO_COLLATERAL_SELECTED: 'You need to choose a collateral.',
  SWAP_FAILED: 'You can try again later or modify slippage.',
  OVER_SLIPPAGE: 'suffer too much slippage try smaller amount of input',
  UNSUPPORTED_ACTION: 'Unsupported action',
  ACTION_FAILED_WITH_ERROR: {
    DEFAULT: 'Get error while execution - ',
    DEPOSIT: 'Get error while depositing - ',
    BORROW: 'Get error while borrowing - ',
    WITHDRAW: 'Get error while withdrawing - ',
    REPAY: 'Get error while repaying - ',
    CREATE: 'Get error while creating position - ',
    CLOSE: 'Get error while closing position - ',
    DESTROY: 'Get error while destroying position - ',
    STAKE: 'Get error while staking - ',
    UNSTAKE: 'Get error while unstaking - ',
    LOCK: 'Get error while locking positions - ',
    UNLOCK: 'Get error while unlocking position - ',
    CLAIM: 'Get error while claiming reward - ',
    SWAP: 'Get error while swapping - ',
    QUOTE: 'Get error while quoting - ',
    CHECK_IN: 'Get error while checking in - ',
    MIGRATE: 'Get error while migration - ',
  },
} as const;
